const buildLyrics = (metadata, lyrics, translations) => ({
  ...metadata,
  lyrics,
  translations,
  availableTranslations: Object.keys(translations || {}),
});

const FIA_TIMELINE = [
  { time: 0, text: 'Fia, Fia', original: 'Fia, Fia' },
  { time: 6000, text: 'Dance make I dance', original: 'Dance make I dance' },
  { time: 12000, text: 'Give me love make I love', original: 'Give me love make I love' },
  { time: 18000, text: 'Shawty want a million dollar (shekpe)', original: 'Shawty want a million dollar (shekpe)' },
  { time: 28000, text: 'You for dey for me when the boy dey hunger', original: 'Yeh!, you for dey for me when the boy dey hunger' },
  { time: 38000, text: '"If you no get money, hide your face"', original: '"If you no get money, hide your face"' },
  { time: 48000, text: 'I love you no mean say make I enter fire', original: 'I love you no mean say if you say make I put hand for fire' },
  { time: 60000, text: 'Caroline save your drama, I no need am', original: 'Caroline save your drama, I do not need it' },
  { time: 70000, text: 'Hola Mr Olopa, no wahala', original: 'Hola, Hola, Mr Olopa, am not here to cause wahala' },
  { time: 82000, text: 'Dance make I dance (reprise)', original: 'Dance make I dance, give me love make I love' },
  { time: 92000, text: 'You for dey for me (reprise)', original: 'Yeh!, you for dey for me (you for dey)' },
  { time: 102000, text: 'I hide my face, make another man pikin run my race', original: 'I hide my face, make another man pikin run my race' },
];

const FIA_TRANSLATIONS = {
  english: [
    { time: 0, text: 'Fia, Fia dance, let me dance' },
    { time: 6000, text: 'Give me love, let me love' },
    { time: 12000, text: 'Do not place anyone else above me' },
    { time: 18000, text: 'She wants a million dollars wired today' },
    { time: 28000, text: 'You should have been there when I was hungry' },
    { time: 38000, text: '"If you have no money, hide your face"' },
    { time: 48000, text: '"I love you" does not mean I will walk through fire' },
    { time: 60000, text: 'Caroline, keep the drama for the soap opera' },
    { time: 70000, text: 'Officer, I am not here to make trouble' },
    { time: 82000, text: 'Let me dance and love freely' },
    { time: 92000, text: 'You should have been there when I was down' },
    { time: 102000, text: 'I hid my face so someone else could run my race' },
  ],
  french: [
    { time: 0, text: 'Fia, Fia, laisse-moi danser' },
    { time: 6000, text: 'Donne-moi de l amour, ne mets personne au-dessus' },
    { time: 12000, text: 'Elle veut un million de dollars et un virement' },
    { time: 28000, text: 'Tu aurais du etre la quand j avais faim' },
    { time: 38000, text: '"Si tu n as pas d argent, cache ton visage"' },
    { time: 48000, text: '"Je t aime" ne veut pas dire que je brule pour toi' },
    { time: 60000, text: 'Caroline, garde ton drame' },
    { time: 70000, text: 'Bonjour policier, pas de probleme ici' },
    { time: 82000, text: 'Laisse-moi danser et aimer librement' },
    { time: 92000, text: 'Tu aurais du rester quand j etais pauvre' },
    { time: 102000, text: 'J ai cache mon visage, j ai laisse un autre courir ma course' },
  ],
  yoruba: [
    { time: 0, text: 'Fia, Fia, je ki n jo' },
    { time: 6000, text: 'Fun mi ni ife, ma fi elomiran s oke' },
    { time: 12000, text: 'O ni ki n ranse fun un ni milionu dola' },
    { time: 28000, text: 'O ye ki o wa nigba ti ebi npa mi' },
    { time: 38000, text: '"Ti o ko ba ni owo, ti oju re mo"' },
    { time: 48000, text: '"Mo ni fe re" ko tumo si ki n wo inu ina' },
    { time: 60000, text: 'Caroline, dake sile pelu drama' },
    { time: 70000, text: 'Mr Olopa, mi o wa fa wahala' },
    { time: 82000, text: 'Je ki n jo, ki n ni fe ni alaafia' },
    { time: 92000, text: 'O ye ki o duro nigba ti mo wa ni isoro' },
    { time: 102000, text: 'Mo ti oju mi mo ki elomiran sare idije mi' },
  ],
  spanish: [
    { time: 0, text: 'Fia, Fia, deja que baile' },
    { time: 6000, text: 'Dame amor y no pongas a nadie encima' },
    { time: 12000, text: 'Ella quiere un millon y que lo transfiera' },
    { time: 28000, text: 'Debiste estar cuando tenia hambre' },
    { time: 38000, text: '"Si no tienes dinero, oculta tu rostro"' },
    { time: 48000, text: '"Te amo" no significa que caminare en fuego' },
    { time: 60000, text: 'Caroline, guarda tu drama' },
    { time: 70000, text: 'Hola oficial, no vengo a causar problemas' },
    { time: 82000, text: 'Dejame bailar y amar en paz' },
    { time: 92000, text: 'Debiste quedarte cuando era pobre' },
    { time: 102000, text: 'Oculte mi rostro para que otro corriera mi carrera' },
  ],
  korean: [
    { time: 0, text: 'Pia pia chum chuge hae' },
    { time: 6000, text: 'Sarang eul jwo, dareun saram wiae duji ma' },
    { time: 12000, text: 'Geunyeoneun bae kman dollar wa songgeumeul wonhae' },
    { time: 28000, text: 'Baegopeul ttae neoneun nae gyeote isseoya haesseo' },
    { time: 38000, text: '"Don eopseumyeon eolgul sumgyeo" rago haetji' },
    { time: 48000, text: '"Saranghae" ga bul sogeuro dulleoganeun deut eun aniya' },
    { time: 60000, text: 'Caroline, deurama neun pillyo eopseo' },
    { time: 70000, text: 'Gyeongchalgwan-nim, munje ireukil byeon aniya' },
    { time: 82000, text: 'Chum chugo saranghage hae jwo' },
    { time: 92000, text: 'Nega himdeul ttae neoneun isseoya haesseo' },
    { time: 102000, text: 'Naneun eolgul eumgo dareun sarami ddaerige haesseo' },
  ],
};

const ALL_THE_STARS_TIMELINE = [
  { time: 0, text: 'Love, lets talk about love', original: 'Love, letâ€™s talk about love' },
  { time: 8000, text: 'Is it everything you hoped for?', original: 'Is it anything and everything you hoped for?' },
  { time: 16000, text: 'Do the feelings haunt you?', original: 'Or do the feeling haunt you?' },
  { time: 24000, text: 'This may be the night my dreams let me know', original: 'This may be the night that my dreams might let me know' },
  { time: 32000, text: 'All the stars are closer', original: 'All the stars are closer' },
  { time: 42000, text: 'Tell me what you gon do to me', original: 'Tell me what you gonâ€™ do to me' },
  { time: 52000, text: 'Confrontation aint new to me', original: 'Confrontation ainâ€™t nothinâ€™ new to me' },
  { time: 62000, text: 'Corrupt a mans heart with a gift', original: 'Corrupt a manâ€™s heart with a gift' },
  { time: 72000, text: 'I want the credit if Im losin or Im winnin', original: 'I want the credit if Iâ€™m losinâ€™, or Iâ€™m winninâ€™' },
  { time: 82000, text: 'Skin covered in ego, I get involved', original: 'Skin covered in ego, get to talkinâ€™, I get involved' },
  { time: 92000, text: 'You make me feel loved like no one else', original: 'Itâ€™s the way that you making me feel like nobody ever loved me' },
  { time: 102000, text: 'Better live your life, time is running out', original: 'Better live your life, we are running outta time' },
];

const ALL_THE_STARS_TRANSLATIONS = {
  english: [
    { time: 0, text: 'Love, lets really talk about it' },
    { time: 8000, text: 'Is it what you dreamed of?' },
    { time: 16000, text: 'Do the ghosts still follow you?' },
    { time: 24000, text: 'Tonight my dreams might speak' },
    { time: 32000, text: 'All the stars feel near' },
    { time: 42000, text: 'Tell me what you plan for me' },
    { time: 52000, text: 'Conflict is nothing new for me' },
    { time: 62000, text: 'A gift can corrupt the heart' },
    { time: 72000, text: 'Give me the credit win or lose' },
    { time: 82000, text: 'My ego-covered skin jumps in' },
    { time: 92000, text: 'You make me feel uniquely loved' },
    { time: 102000, text: 'Live your life, time is short' },
  ],
  french: [
    { time: 0, text: 'Amour, parlons vraiment d amour' },
    { time: 8000, text: 'Est-ce tout ce que tu esperais ?' },
    { time: 16000, text: 'Ce sentiment te hante-t-il encore ?' },
    { time: 24000, text: 'Cette nuit, mes reves me parleront peut-etre' },
    { time: 32000, text: 'Toutes les etoiles se rapprochent' },
    { time: 42000, text: 'Dis-moi ce que tu feras de moi' },
    { time: 52000, text: 'La confrontation mest familiere' },
    { time: 62000, text: 'Un cadeau peut corrompre un coeur' },
    { time: 72000, text: 'Je veux le merite, victoire ou defaite' },
    { time: 82000, text: 'Ma peau d ego s en mele encore' },
    { time: 92000, text: 'Tu me fais sentir aime comme jamais' },
    { time: 102000, text: 'Vis ta vie, le temps nous echappe' },
  ],
  yoruba: [
    { time: 0, text: 'Ife, e je ka soro nipa re' },
    { time: 8000, text: 'Se ero re lo se?' },
    { time: 16000, text: 'Se imolara naa n pa o?' },
    { time: 24000, text: 'O seese ko je ale yi ti ala yoo so' },
    { time: 32000, text: 'Gbogbo irawo wa nitosi' },
    { time: 42000, text: 'So fun mi ohun ti o maa se si mi' },
    { time: 52000, text: 'Ija ko je nkan tuntun si mi' },
    { time: 62000, text: 'Ebun le ba okan je' },
    { time: 72000, text: 'Fun mi ni kika boya mo segun tabi padanu' },
    { time: 82000, text: 'Ara mi ti kun fun igberaga tun wa' },
    { time: 92000, text: 'O je ki n mo ife gidi' },
    { time: 102000, text: 'Gbe igbese aye re, akoko n lo' },
  ],
  spanish: [
    { time: 0, text: 'Amor, hablemos del amor' },
    { time: 8000, text: 'Es todo lo que esperabas?' },
    { time: 16000, text: 'Ese sentimiento aun te persigue?' },
    { time: 24000, text: 'Esta noche mis suenos quiza hablen' },
    { time: 32000, text: 'Todas las estrellas estan mas cerca' },
    { time: 42000, text: 'Dime que vas a hacer conmigo' },
    { time: 52000, text: 'La confrontacion no es nueva para mi' },
    { time: 62000, text: 'Un regalo puede corromper el corazon' },
    { time: 72000, text: 'Quiero el credito gane o pierda' },
    { time: 82000, text: 'Mi ego vuelve a involucrarse' },
    { time: 92000, text: 'Me haces sentir amado como nadie' },
    { time: 102000, text: 'Vive tu vida, el tiempo se acaba' },
  ],
};

const TITI_TIMELINE = [
  { time: 0, text: 'Titi me pregunto si tengo muchas novias', original: 'Titi me pregunto si tengo muchas novias' },
  { time: 7000, text: 'Hoy tengo a una, manana otra', original: 'Hoy tengo a una, manana otra' },
  { time: 14000, text: 'Pero no hay boda', original: 'Pero no hay boda' },
  { time: 21000, text: 'Me las voy a llevar a todas pa un VIP', original: 'Me las voy a llevar a todas pa un VIP' },
  { time: 28000, text: 'Saluden a Titi, vamos a tirarno un selfi', original: 'Ey, saluden a Titi, vamo a tirarno un selfi' },
  { time: 36000, text: 'Me gustan las Gabriela, Patricia, Nicole, Sofia', original: 'Me gustan mucho las Gabriela, las Patricia, las Sofia' },
  { time: 44000, text: 'Tengo una colombiana que escribe todos los dias', original: 'Tengo una colombiana que me escribe todos los dias' },
  { time: 52000, text: 'Otra en San Antonio que me quiere todavia', original: 'Otra en San Antonio que me quiere todavia' },
  { time: 60000, text: 'Una dominicana que es uva bombon', original: 'Una dominicana que es uva bombon' },
  { time: 68000, text: 'La de Barcelona dice que mi bicho esta cabron', original: 'La de Barcelona que vino en avion dice que mi bicho esta cabron' },
  { time: 76000, text: 'Dejo que jueguen con mi corazon', original: 'Yo dejo que jueguen con mi corazon' },
  { time: 84000, text: 'El dia que me case te envio la invitacion', original: 'El dia que me case te envio la invitacion' },
];

const TITI_TRANSLATIONS = {
  english: [
    { time: 0, text: 'Titi asked if I have many girlfriends' },
    { time: 7000, text: 'Today one, tomorrow another' },
    { time: 14000, text: 'But there is no wedding' },
    { time: 21000, text: 'I will take them all to the VIP' },
    { time: 28000, text: 'Say hi to Titi, lets take a selfie' },
    { time: 36000, text: 'I like the Gabrielas, Patricias, Nicoles, Sofias' },
    { time: 44000, text: 'A Colombian texts me every day' },
    { time: 52000, text: 'Another in San Antonio still loves me' },
    { time: 60000, text: 'A Dominican girl sweet like a grape' },
    { time: 68000, text: 'The one from Barcelona says my vibe is crazy' },
    { time: 76000, text: 'I let them play with my heart' },
    { time: 84000, text: 'When I marry I will send the invite' },
  ],
  french: [
    { time: 0, text: 'Titi m a demande si j ai beaucoup de copines' },
    { time: 7000, text: 'Aujourd hui une, demain une autre' },
    { time: 14000, text: 'Mais il n y aura pas de mariage' },
    { time: 21000, text: 'Je les emmene toutes au VIP' },
    { time: 28000, text: 'Saluez Titi, faisons un selfie' },
    { time: 36000, text: 'Jaime Gabriela, Patricia, Nicole, Sofia' },
    { time: 44000, text: 'Une Colombienne m ecrit chaque jour' },
    { time: 52000, text: 'A San Antonio, une autre maime encore' },
    { time: 60000, text: 'Une Dominicaine douce comme un raisin' },
    { time: 68000, text: 'Celle de Barcelone dit que je suis incroyable' },
    { time: 76000, text: 'Je les laisse jouer avec mon coeur' },
    { time: 84000, text: 'Le jour ou je me marie, tu auras linvitation' },
  ],
  yoruba: [
    { time: 0, text: 'Titi beere boya mo ni opolopo orebirin' },
    { time: 7000, text: 'Loni á»kan, ola mii' },
    { time: 14000, text: 'Sugbon igbeyawo ko si' },
    { time: 21000, text: 'Emi yoo mu won lo si VIP' },
    { time: 28000, text: 'E ki Titi, e ya selfie' },
    { time: 36000, text: 'Mo fe Gabriela, Patricia, Nicole, Sofia' },
    { time: 44000, text: 'Omobirin Kolombia n ko si mi lojoojumá»' },
    { time: 52000, text: 'Ni San Antonio elomiran á¹£i fe mi' },
    { time: 60000, text: 'Dominicana kan dabi opo awon' },
    { time: 68000, text: 'Tii wa lati Barcelona so pe mo buru gan' },
    { time: 76000, text: 'Mo je ki won sere pelu okan mi' },
    { time: 84000, text: 'Ni ojo ti mo ba fe, maa ran iwe ipe' },
  ],
  spanish: [
    { time: 0, text: 'Titi me pregunto si tengo muchas novias' },
    { time: 7000, text: 'Hoy una, manana otra' },
    { time: 14000, text: 'Pero no hay boda' },
    { time: 21000, text: 'Las llevo a todas a un VIP' },
    { time: 28000, text: 'Saluden a Titi, selfie y "cheese"' },
    { time: 36000, text: 'Me encantan Gabriela, Patricia, Nicole, Sofia' },
    { time: 44000, text: 'Una colombiana me escribe diario' },
    { time: 52000, text: 'En San Antonio aun me quieren' },
    { time: 60000, text: 'Una dominicana dulce como uva' },
    { time: 68000, text: 'La de Barcelona dice que soy increible' },
    { time: 76000, text: 'Los dejo jugar con mi corazon' },
    { time: 84000, text: 'Cuando me case, te mandare la invitacion' },
  ],
};

export const MOCK_LYRICS = {
  'davido-fia': buildLyrics(
    {
      songId: 'davido-fia',
      title: 'FIA',
      artist: 'Davido',
      album: 'A Good Time',
      duration: 205000,
    },
    FIA_TIMELINE,
    FIA_TRANSLATIONS,
  ),
  'kendrick-all-the-stars': buildLyrics(
    {
      songId: 'kendrick-all-the-stars',
      title: 'All The Stars',
      artist: 'Kendrick Lamar & SZA',
      album: 'Black Panther',
      duration: 230000,
    },
    ALL_THE_STARS_TIMELINE,
    ALL_THE_STARS_TRANSLATIONS,
  ),
  'badbunny-titi': buildLyrics(
    {
      songId: 'badbunny-titi',
      title: 'Titi Me Pregunto',
      artist: 'Bad Bunny',
      album: 'Un Verano Sin Ti',
      duration: 240000,
    },
    TITI_TIMELINE,
    TITI_TRANSLATIONS,
  ),
};

export default MOCK_LYRICS;
